/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.rsd.plumbing;

public final class R {
    public static final class animator {
        public static final int fade_in_and_scale_up=0x7f040000;
        public static final int fade_out_and_scale_down=0x7f040001;
        public static final int slide_in_bottom=0x7f040002;
        public static final int slide_out_bottom=0x7f040003;
    }
    public static final class array {
        public static final int length_activity_options=0x7f090000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f050001;
        public static final int black_transparent=0x7f050002;
        public static final int white=0x7f050000;
    }
    public static final class dimen {
        /**  Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively). 
         */
        public static final int activity_horizontal_margin=0x7f060007;
        /**  Image sized 
         */
        public static final int image_pipe_size=0x7f060006;
        /**  Default screen margins, per the Android Design guidelines. 
         */
        public static final int padding_standard=0x7f060000;
        public static final int padding_standard_half=0x7f060001;
        public static final int text_size_large=0x7f060005;
        public static final int text_size_medium=0x7f060004;
        /**  Default text sizes 
         */
        public static final int text_size_micro=0x7f060002;
        public static final int text_size_small=0x7f060003;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
        public static final int icon_plumbing=0x7f020001;
        public static final int pipes3=0x7f020002;
        public static final int pipes4=0x7f020003;
        public static final int pipes5=0x7f020004;
        public static final int pipes6=0x7f020005;
        public static final int pipes7=0x7f020006;
    }
    public static final class id {
        public static final int action_settings=0x7f0c0009;
        public static final int button_gradient_calculation=0x7f0c0007;
        public static final int container_length_details=0x7f0c0004;
        public static final int gridview_pipesize=0x7f0c0008;
        public static final int imageview_pipe=0x7f0c0002;
        public static final int label_calculated_gradient=0x7f0c0000;
        public static final int label_length=0x7f0c0005;
        public static final int label_number_of_clips=0x7f0c0001;
        public static final int label_pipe_size=0x7f0c0003;
        public static final int seekbar_length=0x7f0c0006;
    }
    public static final class integer {
        public static final int animation_duration_default=0x7f070000;
    }
    public static final class layout {
        public static final int activity_calculation=0x7f030000;
        public static final int activity_length=0x7f030001;
        public static final int activity_main=0x7f030002;
        public static final int gridview_pipe_item=0x7f030003;
        public static final int item_actionbar_spinner=0x7f030004;
    }
    public static final class menu {
        public static final int main=0x7f0b0000;
    }
    public static final class string {
        public static final int action_settings=0x7f080002;
        public static final int app_name=0x7f080000;
        public static final int button_calculation=0x7f080004;
        public static final int hello_world=0x7f080001;
        public static final int label_default_length_prompt=0x7f080003;
    }
    public static final class style {
        /**  Base application theme. 
 Customize your theme here. 
         */
        public static final int AppTheme=0x7f0a0000;
        public static final int match_parent=0x7f0a0001;
        /** <item name="android:windowNoTitle">true</item>
<item name="android:windowIsTranslucent">true</item>
<item name="android:windowBackground">@android:color/transparent</item>
         */
        public static final int transparent=0x7f0a0003;
        public static final int wrap_parent=0x7f0a0002;
    }
}
